---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-a-task1
spec:
  replicas: 2
  selector:
    matchLabels:
      name:  plan-a-task1
  template:
    metadata:
      labels:
        name:  plan-a-task1
    spec:
      containers:
        - name: application
          image: siresimon/plan-a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081          
---
apiVersion: v1
kind: Service
metadata:
  name: plana-task1-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    name:  plan-a-task1
